title: Xin (David) Zhao
logo: /assets/img/profile-pic-real.png
description: I am a microbiologist-turned-bioinformatician with a PhD in Food Science, specializing in data analysis and software development to empower biologists in understanding their data.
show_downloads: false
# google_analytics:
theme: jekyll-theme-minimal