title: Xin (David) Zhao
logo: /assets/img/profile-pic-real.png
description: I am a bioinformatician with a PhD in microbiology. I help life science researchers make precise and efficient discoveries by providing robust and reproducible data analysis solutions. I develop and utilize advanced computational tools, allowing scientists to concentrate on innovation and experimentation without the burden of complex data challenges.
show_downloads: false
# google_analytics:
theme: jekyll-theme-minimal